
- name: Restart prometheus container
  community.docker.docker_compose_v2:
    project_src: /tmp/
    files:
      - docker-compose.yml
    state: restarted
    services:
      - prometheus

- name: Restart grafana container 
  community.docker.docker_compose_v2:
    project_src: /tmp/
    files:
      - docker-compose.yml
    state: restarted
    services:
      - grafana
