- name: Make sure the folder of the keyrings exists
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: /etc/apt/keyrings

- name: Ensure dpkg installed
  ansible.builtin.apt:
    name: dpkg
    state: present

- name: Delete old kernel images to free /boot partition to be able to upgrade
  become_user: root
  ansible.builtin.shell:
    cmd: dpkg -l linux-image* | grep ii | grep -v `uname -r` | awk '{ print $2 }' | xargs apt -y purge

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: APT upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Get key to Docker's APT repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest
    allow_downgrade: true
  notify: Restart docker

- name: Ensure Docker is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure docker users are added to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
      
